# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bharatagri-cod-form"
client_id = "0a4f33d76e6fccd9e087716b261a0f8f"
application_url = "https://f03a-2401-4900-1cba-99c3-a148-ce25-7d57-a14c.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://f03a-2401-4900-1cba-99c3-a148-ce25-7d57-a14c.ngrok-free.app/auth/callback",
  "https://f03a-2401-4900-1cba-99c3-a148-ce25-7d57-a14c.ngrok-free.app/auth/shopify/callback",
  "https://f03a-2401-4900-1cba-99c3-a148-ce25-7d57-a14c.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-322972d3.myshopify.com"
